USE bsuir_dbms;

CREATE TABLE Users
(
    Id INT PRIMARY KEY IDENTITY,
    UserName NVARCHAR(50) NOT NULL, 
    Email NVARCHAR(50) NOT NULL,
);
 
CREATE TABLE Cards
(
    Id INT PRIMARY KEY IDENTITY,
    OwnerId INT NOT NULL,
    CardNumber CHAR(16) NOT NULL,
	CardMonth CHAR(2) NOT NULL,
	CardYear CHAR(4) NOT NULL,
	CardCvv CHAR(3) NOT NULL,
	FOREIGN KEY (OwnerId) REFERENCES Users (Id)
);

CREATE TABLE Wallets
(
    Id INT PRIMARY KEY IDENTITY,
    OwnerId INT NOT NULL,
    Number NVARCHAR(16) NOT NULL,
	Balance FLOAT NOT NULL,
	FOREIGN KEY (OwnerId) REFERENCES Users (Id)
);

CREATE TABLE Transfers
(
    Id INT PRIMARY KEY IDENTITY,
    RecieverId INT NOT NULL,
	SenderId INT NOT NULL,
    Amount FLOAT NOT NULL,
	TransferDate DATETIME NOT NULL CONSTRAINT DF_Transfer_Date DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (RecieverId) REFERENCES Wallets (Id),
	FOREIGN KEY (SenderId) REFERENCES Wallets (Id)
);

CREATE TABLE Deposits
(
    Id INT PRIMARY KEY IDENTITY,
    SourceId INT NOT NULL,
    ReceiverId INT NOT NULL,
	Amount FLOAT NOT NULL,
	DepositDate DATETIME NOT NULL CONSTRAINT DF_Deposit_Date DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (SourceId) REFERENCES Cards (Id),
	FOREIGN KEY (ReceiverId) REFERENCES Wallets (Id)
);

CREATE TABLE Withdrawals
(
    Id INT PRIMARY KEY IDENTITY,
    SenderId INT NOT NULL,
	ReceiverId INT NOT NULL,
	Amount FLOAT NOT NULL,
	DepositDate DATETIME NOT NULL CONSTRAINT DF_Withdrawal_Date DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (ReceiverId) REFERENCES Cards (Id),
	FOREIGN KEY (SenderId) REFERENCES Wallets (Id)
);

CREATE TABLE Moneyboxes
(
    Id INT PRIMARY KEY IDENTITY,
    Number NVARCHAR(16) NOT NULL,
	Balance FLOAT NOT NULL,
	MoneyboxName NVARCHAR(50) NOT NULL,
	Desciption NVARCHAR(256) NOT NULL,
	OwnerId INT NOT NULL,
	Amount FLOAT NOT NULL,
	FOREIGN KEY (OwnerId) REFERENCES Users (Id)
);

CREATE TABLE Donations
(
    Id INT PRIMARY KEY IDENTITY,
    SenderId INT NOT NULL,
	ReceiverId INT NOT NULL,
	Amount FLOAT NOT NULL,
	DepositDate DATETIME NOT NULL CONSTRAINT DF_Donation_Date DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (ReceiverId) REFERENCES Moneyboxes (Id),
	FOREIGN KEY (SenderId) REFERENCES Wallets (Id)
);

CREATE TABLE Roles
(
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(50) NOT NULL
);

CREATE TABLE UserRoles
(
    UserId INT NOT NULL,
	RoleId INT NOT NULL,
	CONSTRAINT PK_UserRoles PRIMARY KEY CLUSTERED (UserId ASC, RoleId ASC),
	CONSTRAINT FK_Roles_RoleId FOREIGN KEY (RoleId) REFERENCES Roles (Id) ON DELETE CASCADE,
	CONSTRAINT FK_Roles_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE CASCADE
);